% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Analysis of Police Related Death From 2015 to 2016},
  pdfauthor={G.Zhu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Analysis of Police Related Death From 2015 to 2016}
\author{G.Zhu}
\date{6/3/2020}

\begin{document}
\maketitle

\hypertarget{r-markdown-introduction}{%
\subsection{R Markdown Introduction}\label{r-markdown-introduction}}

To better understand the topics of police related death in the US. We
collected the datasets from kaggle (data science/ML training and file
exchange website) to analyze the detail statistics of police related
death between the year of 2015 and 2016. All analysis are subjective to
the data we received from Kaggle. Each visualization and analysis will
be accompanied by short descriptions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Read in 2015 and 2016 police related death data files. Data files are
  stored in .csv format and no modification were made when downloaded
  from Kaggle.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{infile_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'/Users/gezhu/Desktop/police_brutality_analytics/datasets_617_1199_2015.csv'}\NormalTok{)}
\NormalTok{infile_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{'/Users/gezhu/Desktop/police_brutality_analytics/datasets_617_1199_2016.csv'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{victim-profile---average-age-of-the-victim}{%
\subsection{Victim profile - Average age of the
victim}\label{victim-profile---average-age-of-the-victim}}

We would like to know the average, range, and standard deviation of the
victim's age between 2015 and 2016. In order to understand the in depth
information about the victim age, we have to eliminate the rows with
`unknown' age data.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Mean (Average of 2015 victim age) = 37.12073
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(}\StringTok{"stringr"}\NormalTok{)}
\NormalTok{age_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2015}\NormalTok{[,}\DecValTok{3}\NormalTok{]}
\NormalTok{clean_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{str_remove}\NormalTok{(age_}\DecValTok{2015}\NormalTok{, }\StringTok{"Unknown"}\NormalTok{)}
\NormalTok{num_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{(clean_}\DecValTok{2015}\NormalTok{)}
\NormalTok{filtered_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(num_}\DecValTok{2015}\NormalTok{)}
\NormalTok{mean_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(filtered_}\DecValTok{2015}\NormalTok{)}
\NormalTok{mean_}\DecValTok{2015}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 37.12073
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Range (Youngest to oldest victim of 2015) Oldest victim: 87 years old
  Youngest victim: 6 years old Range: (6 - 87)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{min_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{min}\NormalTok{(filtered_}\DecValTok{2015}\NormalTok{)}
\NormalTok{max_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{max}\NormalTok{(filtered_}\DecValTok{2015}\NormalTok{)}
\NormalTok{range_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{range}\NormalTok{(filtered_}\DecValTok{2015}\NormalTok{)}
\NormalTok{range_}\DecValTok{2015}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  6 87
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Standard Deviation Standard deviation of 2015 victim age = 13.25565
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sd_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{sd}\NormalTok{(filtered_}\DecValTok{2015}\NormalTok{)}
\NormalTok{sd_}\DecValTok{2015}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 13.25565
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Repeat the above protocols for 2016 data Average age of 2016 victim:
  36.72071 Range of the age: Youngest 10 and oldest 87 Standard
  deviation of 2016 age: 13.00465
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(}\StringTok{"stringr"}\NormalTok{)}
\NormalTok{age_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2016}\NormalTok{[,}\DecValTok{3}\NormalTok{]}
\NormalTok{clean_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{str_remove}\NormalTok{(age_}\DecValTok{2016}\NormalTok{, }\StringTok{"Unknown"}\NormalTok{)}
\NormalTok{num_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{(clean_}\DecValTok{2016}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: NAs introduced by coercion
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{filtered_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(num_}\DecValTok{2016}\NormalTok{)}
\NormalTok{mean_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(filtered_}\DecValTok{2016}\NormalTok{)}

\NormalTok{range_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{range}\NormalTok{(filtered_}\DecValTok{2016}\NormalTok{)}

\NormalTok{sd_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{sd}\NormalTok{(filtered_}\DecValTok{2016}\NormalTok{)}

\NormalTok{mean_}\DecValTok{2016}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36.72071
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{range_}\DecValTok{2016}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10 87
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sd_}\DecValTok{2016}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 13.00465
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Visualization of Victim Age The barplot shows the frequency of 2015
  victim age. Majority of the victims are in their mid 20s to mid 30s.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(MASS)}
\NormalTok{dataViz =}\StringTok{ }\NormalTok{infile_}\DecValTok{2015}\OperatorTok{$}\NormalTok{age}
\NormalTok{dataViz.freq =}\StringTok{ }\KeywordTok{table}\NormalTok{(dataViz)}
\KeywordTok{barplot}\NormalTok{(dataViz.freq)}
\end{Highlighting}
\end{Shaded}

\includegraphics{2016_pie_files/figure-latex/unnamed-chunk-6-1.pdf} \#\#
Victim Demographics Now we can analyze the demographics of the victim
from 2015 and 2016 police brutality data. 1. Basic demographics
breakdown

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{race_data_}\DecValTok{15}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2015}\NormalTok{[,}\DecValTok{5}\NormalTok{]}
\NormalTok{race_data_}\DecValTok{16}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2016}\NormalTok{[,}\DecValTok{5}\NormalTok{]}
\KeywordTok{table}\NormalTok{(race_data_}\DecValTok{15}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## race_data_15
##          Arab-American Asian/Pacific Islander                  Black 
##                      4                     24                    307 
##        Hispanic/Latino        Native American                  Other 
##                    195                     13                      1 
##                Unknown                  White 
##                     18                    584
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(race_data_}\DecValTok{16}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## race_data_16
##          Arab-American Asian/Pacific Islander                  Black 
##                      3                     21                    261 
##        Hispanic/Latino        Native American                Unknown 
##                    183                     21                     25 
##                  White 
##                    566
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{race_df_}\DecValTok{15}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(race_data_}\DecValTok{15}\NormalTok{))}
\NormalTok{race_df_}\DecValTok{16}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(race_data_}\DecValTok{16}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Visualization of demographics The piechart shows the demographics data
  of police brutality victims between the year of 2015 and 2016.
\end{enumerate}

\begin{itemize}
\tightlist
\item
  2015 demographics pie chart
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\NormalTok{bp_}\DecValTok{15}\NormalTok{<-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(race_df_}\DecValTok{15}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\StringTok{""}\NormalTok{, }\DataTypeTok{y=}\NormalTok{Freq, }\DataTypeTok{fill=}\NormalTok{race_data_}\DecValTok{15}\NormalTok{))}\OperatorTok{+}
\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{width =} \DecValTok{1}\NormalTok{, }\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{)}
\NormalTok{pie_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\NormalTok{bp_}\DecValTok{15} \OperatorTok{+}\StringTok{ }\KeywordTok{coord_polar}\NormalTok{(}\StringTok{"y"}\NormalTok{, }\DataTypeTok{start=}\DecValTok{0}\NormalTok{)}
\NormalTok{pie_}\DecValTok{15}\NormalTok{ <-}\StringTok{ }\NormalTok{pie }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"#999999"}\NormalTok{, }\StringTok{"#E69F00"}\NormalTok{, }\StringTok{"#56B4E9"}\NormalTok{, }\StringTok{"#7a425c"}\NormalTok{, }\StringTok{"#61137d"}\NormalTok{, }\StringTok{"#cf4240"}\NormalTok{, }\StringTok{"#c8cf40"}\NormalTok{, }\StringTok{"#e6f1f2"}\NormalTok{))}
\NormalTok{pie_}\DecValTok{15}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## NULL
\end{verbatim}

\begin{itemize}
\tightlist
\item
  2016 demographics pie chart
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bp_}\DecValTok{16}\NormalTok{ <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(race_df_}\DecValTok{16}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\StringTok{""}\NormalTok{, }\DataTypeTok{y=}\NormalTok{Freq, }\DataTypeTok{fill=}\NormalTok{race_data_}\DecValTok{16}\NormalTok{))}\OperatorTok{+}
\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{width =} \DecValTok{1}\NormalTok{, }\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{)}
\NormalTok{pie_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\NormalTok{bp_}\DecValTok{16} \OperatorTok{+}\StringTok{ }\KeywordTok{coord_polar}\NormalTok{(}\StringTok{"y"}\NormalTok{, }\DataTypeTok{start=}\DecValTok{0}\NormalTok{)}
\NormalTok{pie_}\DecValTok{16}\NormalTok{ <-}\StringTok{ }\NormalTok{pie }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"#999999"}\NormalTok{, }\StringTok{"#E69F00"}\NormalTok{, }\StringTok{"#56B4E9"}\NormalTok{, }\StringTok{"#7a425c"}\NormalTok{, }\StringTok{"#61137d"}\NormalTok{, }\StringTok{"#cf4240"}\NormalTok{, }\StringTok{"#c8cf40"}\NormalTok{, }\StringTok{"#e6f1f2"}\NormalTok{))}
\NormalTok{pie_}\DecValTok{16}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## NULL
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Gender of the victims 2015 victim gender data
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gender_data_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2015}\NormalTok{[,}\DecValTok{4}\NormalTok{]}
\NormalTok{gender_df_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(gender_data_}\DecValTok{2015}\NormalTok{))}
\NormalTok{gender_df_}\DecValTok{2015}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   gender_data_2015 Freq
## 1           Female   52
## 2             Male 1093
## 3   Non-conforming    1
\end{verbatim}

2016 victim gender data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gender_data_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2016}\NormalTok{[,}\DecValTok{4}\NormalTok{]}
\NormalTok{gender_df_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(gender_data_}\DecValTok{2016}\NormalTok{))}
\NormalTok{gender_df_}\DecValTok{2016}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   gender_data_2016 Freq
## 1           Female   58
## 2             Male 1022
\end{verbatim}

\hypertarget{location-of-the-incidents}{%
\subsection{Location of the incidents}\label{location-of-the-incidents}}

Now we can start to look into the location of the incidents. -Incidents
location data from 2015

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{location_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2015}\NormalTok{[,}\DecValTok{12}\NormalTok{]}
\NormalTok{state_data_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(location_}\DecValTok{2015}\NormalTok{))}
\NormalTok{top5_state_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{head}\NormalTok{(state_data_}\DecValTok{2015}\NormalTok{[}\KeywordTok{order}\NormalTok{(}\OperatorTok{-}\NormalTok{state_data_}\DecValTok{2015}\OperatorTok{$}\NormalTok{Freq),],}\DecValTok{5}\NormalTok{))}
\NormalTok{top5_state_}\DecValTok{2015} 
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    location_2015 Freq
## 5             CA  211
## 44            TX  112
## 10            FL   71
## 4             AZ   44
## 11            GA   39
\end{verbatim}

-Incidents data from 2016 We select the top five states with highest
police shooting incidents for visualizations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{location_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2016}\NormalTok{[,}\DecValTok{12}\NormalTok{]}
\NormalTok{state_data_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(location_}\DecValTok{2016}\NormalTok{))}
\NormalTok{top5_state_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{head}\NormalTok{(state_data_}\DecValTok{2016}\NormalTok{[}\KeywordTok{order}\NormalTok{(}\OperatorTok{-}\NormalTok{state_data_}\DecValTok{2016}\OperatorTok{$}\NormalTok{Freq),],}\DecValTok{5}\NormalTok{))}
\NormalTok{top5_state_}\DecValTok{2016} 
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    location_2016 Freq
## 5             CA  160
## 44            TX   92
## 10            FL   70
## 4             AZ   49
## 28            NC   36
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Which police department has the highest number of police shooting? We
  can count the incident frequency by going through the data from both
  2015 and 2016. We display the top ten highest fatality in police
  shooting incidents here.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pd_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2015}\NormalTok{[,}\DecValTok{16}\NormalTok{]}
\NormalTok{pd_data_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(pd_}\DecValTok{2015}\NormalTok{))}
\NormalTok{top10_}\DecValTok{2015}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{head}\NormalTok{(pd_data_}\DecValTok{2015}\NormalTok{[}\KeywordTok{order}\NormalTok{(}\OperatorTok{-}\NormalTok{pd_data_}\DecValTok{2015}\OperatorTok{$}\NormalTok{Freq),],}\DecValTok{10}\NormalTok{))}
\NormalTok{top10_}\DecValTok{2015}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                         pd_2015 Freq
## 386               Los Angeles Police Department   22
## 384     Los Angeles County Sheriff's Department   16
## 297                   Houston Police Department   11
## 115                   Chicago Police Department   10
## 473                  New York Police Department   10
## 309 Indianapolis Metropolitan Police Department    9
## 363    Las Vegas Metropolitan Police Department    9
## 30                     Austin Police Department    8
## 491             Oklahoma City Police Department    8
## 532                   Phoenix Police Department    8
\end{verbatim}

2016 data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pd_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\NormalTok{infile_}\DecValTok{2016}\NormalTok{[,}\DecValTok{16}\NormalTok{]}
\NormalTok{pd_data_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{table}\NormalTok{(pd_}\DecValTok{2016}\NormalTok{))}
\NormalTok{top10_}\DecValTok{2016}\NormalTok{ <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{head}\NormalTok{(pd_data_}\DecValTok{2016}\NormalTok{[}\KeywordTok{order}\NormalTok{(}\OperatorTok{-}\NormalTok{pd_data_}\DecValTok{2016}\OperatorTok{$}\NormalTok{Freq),],}\DecValTok{10}\NormalTok{))}
\NormalTok{top10_}\DecValTok{2016}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                     pd_2016 Freq
## 368           Los Angeles Police Department   19
## 367 Los Angeles County Sheriff's Department   17
## 496               Phoenix Police Department   16
## 651                                 Unknown   16
## 115               Chicago Police Department   11
## 444              New York Police Department   11
## 560           San Antonio Police Department    9
## 643                 Tulsa Police Department    8
## 649          United States Marshals Service    8
## 95                California Highway Patrol    7
\end{verbatim}

Visualization of the top ten shooting incident police department 2015:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\NormalTok{bp_pd_}\DecValTok{2015}\NormalTok{<-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(top10_}\DecValTok{2015}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\StringTok{""}\NormalTok{, }\DataTypeTok{y=}\NormalTok{Freq, }\DataTypeTok{fill=}\NormalTok{pd_}\DecValTok{2015}\NormalTok{))}\OperatorTok{+}
\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{width =} \DecValTok{1}\NormalTok{, }\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{)}
\NormalTok{bp_pd_}\DecValTok{2015}
\end{Highlighting}
\end{Shaded}

\includegraphics{2016_pie_files/figure-latex/unnamed-chunk-16-1.pdf}
2016:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\NormalTok{bp_pd_}\DecValTok{2016}\NormalTok{<-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(top10_}\DecValTok{2016}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\StringTok{""}\NormalTok{, }\DataTypeTok{y=}\NormalTok{Freq, }\DataTypeTok{fill=}\NormalTok{pd_}\DecValTok{2016}\NormalTok{))}\OperatorTok{+}
\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{width =} \DecValTok{1}\NormalTok{, }\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{)}
\NormalTok{bp_pd_}\DecValTok{2016}
\end{Highlighting}
\end{Shaded}

\includegraphics{2016_pie_files/figure-latex/unnamed-chunk-17-1.pdf}

In summary:

The basic data are listed below. Detailed demographics and incidents
locations data are attached next to the visualizations above.

-2015 Data Mean age = 37.12073

Range of the age: Youngest 6 and oldest 87

Standard deviation of 2015 victim age = 13.25565

-2016 Data Mean age = 36.72071

Range of the age: Youngest 10 and oldest 87

Standard deviation of 2016 victim age = 13.00465

\end{document}
